import { expect, test } from "@playwright/test";
import { loginAsLocalUser } from "../../helpers/admin";
import { createPublishedCompetition } from "../../helpers/fixtures";
test("owner creates a private round, shares QR/link, and a friend joins", async ({ browser }) => {
  test.setTimeout(90_000);
  const competition = await createPublishedCompetition();
  const ownerContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const owner = await ownerContext.newPage();
  await loginAsLocalUser(owner, "owner@example.test", "/rounds/new");
  const suffix = crypto.randomUUID().slice(0, 7);
  await owner.getByLabel("Name der Tipprunde").fill(`Freunde ${suffix}`);
  await owner.getByLabel("Liga").selectOption({ label: competition.label });
  await owner.getByLabel("Dein Rundennickname").fill("Daniel");
  await owner.getByRole("button", { name: "Private Tipprunde erstellen" }).click();
  await expect(owner.getByRole("heading", { name: `Freunde ${suffix}` })).toBeVisible();
  await owner.getByRole("link", { name: "Runde verwalten" }).click();
  await owner.getByRole("button", { name: "Neuen 7-Tage-Link erzeugen" }).click();
  const url = await owner.locator(".invitation-share__url").innerText();
  await expect(owner.getByRole("img", { name: /QR-Code/ })).toBeVisible();
  const memberContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const member = await memberContext.newPage();
  await member.goto(url);
  await expect(member.getByRole("heading", { name: `Freunde ${suffix}` })).toBeVisible();
  await member.getByRole("link", { name: "Anmelden" }).click();
  await member.getByLabel("E-Mail-Adresse").fill("member@example.test");
  await member.locator('input[name="password"]').fill("LocalFixture42!");
  await member.getByRole("button", { name: "Anmelden" }).click();
  await expect(member.getByRole("heading", { name: "Der Tipprunde beitreten" })).toBeVisible();
  await member.getByLabel("Dein Rundennickname").fill("Kumpel");
  await member.getByRole("button", { name: "Jetzt beitreten" }).click();
  await expect(member.getByText(`Freunde ${suffix}`, { exact: true })).toBeVisible();
  await ownerContext.close();
  await memberContext.close();
});
